Add Mayhem support
mayhemheroes/simd-json pull request #1
Opened 2022-05-16 03:11 UTC by WGibbs15

2022-06-15 03:40 UTC, xansec requested changes
Please make the requested changes.

2022-06-15 03:40 UTC, xansec commented on Mayhemfile
> +project: wgibbs15/simd-json-fuzz
Could you please make sure the project name is generic?

2022-06-15 03:40 UTC, xansec commented on fuzz/Cargo.toml
Can you describe the need for this change?

2022-06-16 05:46 UTC, WGibbs15 commented on fuzz/Cargo.toml
libfuzzer-sys has a current version 0.4, there's no need to use an older version

2022-06-21 18:45 UTC, xansec commented on fuzz/Cargo.toml
Thanks!

2022-06-21 18:45 UTC, merged